[2023-05-02T16:47:25.098+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: prueba_tecnica.transform_data scheduled__2023-05-01T00:30:00+00:00 map_index=1 [queued]>
[2023-05-02T16:47:25.114+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: prueba_tecnica.transform_data scheduled__2023-05-01T00:30:00+00:00 map_index=1 [queued]>
[2023-05-02T16:47:25.115+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T16:47:25.116+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-05-02T16:47:25.117+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T16:47:25.139+0000] {taskinstance.py:1304} INFO - Executing <Mapped(_PythonDecoratedOperator): transform_data> on 2023-05-01 00:30:00+00:00
[2023-05-02T16:47:25.152+0000] {standard_task_runner.py:55} INFO - Started process 179 to run task
[2023-05-02T16:47:25.167+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'prueba_tecnica', 'transform_data', 'scheduled__2023-05-01T00:30:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/data_process/prueba/Prueba_Tecnica.py', '--cfg-path', '/tmp/tmpx8d3ac8w', '--map-index', '1']
[2023-05-02T16:47:25.170+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask transform_data
[2023-05-02T16:47:25.359+0000] {task_command.py:389} INFO - Running <TaskInstance: prueba_tecnica.transform_data scheduled__2023-05-01T00:30:00+00:00 map_index=1 [running]> on host bb7d79814ac7
[2023-05-02T16:47:25.740+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=loliveros
AIRFLOW_CTX_DAG_ID=prueba_tecnica
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-05-01T00:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-01T00:30:00+00:00
[2023-05-02T16:47:25.741+0000] {Prueba_Tecnica.py:119} INFO - Counter: 1 and dim list file path: 2
[2023-05-02T16:47:25.741+0000] {Prueba_Tecnica.py:123} INFO - File path: /tmp/prueba_tecnica/data/raw/Traffic_Flow_Map_Volumes.csv and file path dest: /tmp/prueba_tecnica/data/stage
[2023-05-02T16:47:25.759+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_process/prueba/Prueba_Tecnica.py", line 125, in transform_data
    data = read_csv(file_path)
  File "/opt/airflow/dags/data_process/prueba/utils/general_utils.py", line 24, in read_csv
    df = pd.read_csv(file_path, sep = sep, encoding = encoding, header = header)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 7 fields in line 438, saw 58

[2023-05-02T16:47:25.780+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=prueba_tecnica, task_id=transform_data, map_index=1, execution_date=20230501T003000, start_date=20230502T164725, end_date=20230502T164725
[2023-05-02T16:47:25.803+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 15 for task transform_data (Error tokenizing data. C error: Expected 7 fields in line 438, saw 58
; 179)
[2023-05-02T16:47:25.860+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-02T16:47:25.893+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
