[2023-05-02T17:41:16.733+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: prueba_tecnica.transform_data manual__2023-05-02T17:40:02.106305+00:00 map_index=0 [queued]>
[2023-05-02T17:41:16.770+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: prueba_tecnica.transform_data manual__2023-05-02T17:40:02.106305+00:00 map_index=0 [queued]>
[2023-05-02T17:41:16.773+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T17:41:16.779+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 3
[2023-05-02T17:41:16.780+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T17:41:16.837+0000] {taskinstance.py:1304} INFO - Executing <Mapped(_PythonDecoratedOperator): transform_data> on 2023-05-02 17:40:02.106305+00:00
[2023-05-02T17:41:16.847+0000] {standard_task_runner.py:55} INFO - Started process 1431 to run task
[2023-05-02T17:41:16.866+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'prueba_tecnica', 'transform_data', 'manual__2023-05-02T17:40:02.106305+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/data_process/prueba/Prueba_Tecnica.py', '--cfg-path', '/tmp/tmpigbt3cmi', '--map-index', '0']
[2023-05-02T17:41:16.872+0000] {standard_task_runner.py:83} INFO - Job 92: Subtask transform_data
[2023-05-02T17:41:17.043+0000] {task_command.py:389} INFO - Running <TaskInstance: prueba_tecnica.transform_data manual__2023-05-02T17:40:02.106305+00:00 map_index=0 [running]> on host bb7d79814ac7
[2023-05-02T17:41:17.225+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=loliveros
AIRFLOW_CTX_DAG_ID=prueba_tecnica
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-05-02T17:40:02.106305+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-02T17:40:02.106305+00:00
[2023-05-02T17:41:17.227+0000] {Prueba_Tecnica.py:120} INFO - Counter: 0 and dim list file path: 2
[2023-05-02T17:41:17.228+0000] {Prueba_Tecnica.py:124} INFO - File path: /tmp/prueba_tecnica/data/raw/Traffic_Flow_Map_Volumes20230502.csv and file path dest: /tmp/prueba_tecnica/data/stage
[2023-05-02T17:41:17.276+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_process/prueba/Prueba_Tecnica.py", line 146, in transform_data
    clean_transform_data(df = data,subset_columns=subset_columns,
  File "/opt/airflow/dags/data_process/prueba/utils/general_utils.py", line 40, in clean_transform_data
    collision_count = pd.NamedAgg(
AttributeError: 'NamedAgg' object has no attribute 'reset_index'
[2023-05-02T17:41:17.293+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=prueba_tecnica, task_id=transform_data, map_index=0, execution_date=20230502T174002, start_date=20230502T174116, end_date=20230502T174117
[2023-05-02T17:41:17.336+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 92 for task transform_data ('NamedAgg' object has no attribute 'reset_index'; 1431)
[2023-05-02T17:41:17.363+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-02T17:41:17.463+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
